spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
    open-in-view: false

kakao:
  api:
    key: ${KAKAO_REST_API_KEY}


logging:
  level:
    org.hibernate.SQL: DEBUG
    com.proxbook.finder : DEBUG
    web: DEBUG

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs/ui

opensearch:
  host : ${OPENSEARCH_HOST}
  port : ${OPENSEARCH_PORT}

