spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/proxbook?rewriteBatchedStatements=true&profileSQL=true&maxQuerySizeToLog=12345
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
    open-in-view: false

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    rest:
      uris: localhost:9200

kakao:
  api:
    key: ${KAKAO_REST_API_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.proxbook.finder : DEBUG
    web: DEBUG
