spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/proxbook
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.proxbook.finder : DEBUG
    web: DEBUG
