spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/proxbook
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

kakao:
  api:
    key: ${KAKAO_REST_API_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.proxbook.finder : DEBUG
    web: DEBUG
