services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proxbook
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - prox_book_db:/var/lib/mysql

  es:
    container_name: elasticsearch
    build: ./es
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - es

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    environment: ['xpack.monitoring.enabled: true']
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/jar:/usr/share/logstash/jar
      - ./logstash/template:/usr/share/logstash/template
    depends_on:
      - db
      - es
networks:
  default:
    driver: bridge

volumes:
  prox_book_db:
